// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analyses.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countAnalyses = `-- name: CountAnalyses :one
SELECT COUNT(*)
FROM analyses
WHERE
    workspace_id = $1
    AND deleted_at IS NULL
    AND ($2::text IS NULL OR status = $2)
`

type CountAnalysesParams struct {
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	Status      sql.NullString `json:"status"`
}

func (q *Queries) CountAnalyses(ctx context.Context, arg CountAnalysesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnalyses, arg.WorkspaceID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnalysis = `-- name: CreateAnalysis :one

INSERT INTO analyses (
    workspace_id,
    title,
    description,
    analysis_type,
    status,
    config,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, 'pending', $5, now(), now()
)
RETURNING id, workspace_id, title, description, analysis_type, status, started_at, completed_at, config, error_message, created_at, updated_at, deleted_at
`

type CreateAnalysisParams struct {
	WorkspaceID  uuid.UUID             `json:"workspace_id"`
	Title        string                `json:"title"`
	Description  sql.NullString        `json:"description"`
	AnalysisType string                `json:"analysis_type"`
	Config       pqtype.NullRawMessage `json:"config"`
}

// ========================================
// Analysis Operations
// ========================================
func (q *Queries) CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (Analysis, error) {
	row := q.db.QueryRowContext(ctx, createAnalysis,
		arg.WorkspaceID,
		arg.Title,
		arg.Description,
		arg.AnalysisType,
		arg.Config,
	)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.AnalysisType,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Config,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAnalysisResult = `-- name: CreateAnalysisResult :one

INSERT INTO analysis_results (
    analysis_id,
    result_type,
    content,
    image_url,
    minio_bucket,
    minio_key,
    metadata,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now()
)
RETURNING id, analysis_id, result_type, content, image_url, minio_bucket, minio_key, metadata, created_at
`

type CreateAnalysisResultParams struct {
	AnalysisID  uuid.UUID             `json:"analysis_id"`
	ResultType  string                `json:"result_type"`
	Content     json.RawMessage       `json:"content"`
	ImageUrl    sql.NullString        `json:"image_url"`
	MinioBucket sql.NullString        `json:"minio_bucket"`
	MinioKey    sql.NullString        `json:"minio_key"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

// ========================================
// Analysis Results Operations
// ========================================
func (q *Queries) CreateAnalysisResult(ctx context.Context, arg CreateAnalysisResultParams) (AnalysisResult, error) {
	row := q.db.QueryRowContext(ctx, createAnalysisResult,
		arg.AnalysisID,
		arg.ResultType,
		arg.Content,
		arg.ImageUrl,
		arg.MinioBucket,
		arg.MinioKey,
		arg.Metadata,
	)
	var i AnalysisResult
	err := row.Scan(
		&i.ID,
		&i.AnalysisID,
		&i.ResultType,
		&i.Content,
		&i.ImageUrl,
		&i.MinioBucket,
		&i.MinioKey,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnalysis = `-- name: DeleteAnalysis :exec
UPDATE analyses
SET
    deleted_at = now(),
    updated_at = now()
WHERE 
    id = $1
    AND workspace_id = $2
    AND deleted_at IS NULL
`

type DeleteAnalysisParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteAnalysis(ctx context.Context, arg DeleteAnalysisParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnalysis, arg.ID, arg.WorkspaceID)
	return err
}

const deleteAnalysisResults = `-- name: DeleteAnalysisResults :exec
DELETE FROM analysis_results
WHERE analysis_id = $1
`

func (q *Queries) DeleteAnalysisResults(ctx context.Context, analysisID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAnalysisResults, analysisID)
	return err
}

const getAnalysis = `-- name: GetAnalysis :one
SELECT id, workspace_id, title, description, analysis_type, status, started_at, completed_at, config, error_message, created_at, updated_at, deleted_at FROM analyses
WHERE
    id = $1
    AND workspace_id = $2
    AND deleted_at IS NULL
`

type GetAnalysisParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetAnalysis(ctx context.Context, arg GetAnalysisParams) (Analysis, error) {
	row := q.db.QueryRowContext(ctx, getAnalysis, arg.ID, arg.WorkspaceID)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.AnalysisType,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Config,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAnalysisResult = `-- name: GetAnalysisResult :one
SELECT id, analysis_id, result_type, content, image_url, minio_bucket, minio_key, metadata, created_at FROM analysis_results
WHERE 
    id = $1
    AND analysis_id = $2
`

type GetAnalysisResultParams struct {
	ID         uuid.UUID `json:"id"`
	AnalysisID uuid.UUID `json:"analysis_id"`
}

func (q *Queries) GetAnalysisResult(ctx context.Context, arg GetAnalysisResultParams) (AnalysisResult, error) {
	row := q.db.QueryRowContext(ctx, getAnalysisResult, arg.ID, arg.AnalysisID)
	var i AnalysisResult
	err := row.Scan(
		&i.ID,
		&i.AnalysisID,
		&i.ResultType,
		&i.Content,
		&i.ImageUrl,
		&i.MinioBucket,
		&i.MinioKey,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAnalyses = `-- name: ListAnalyses :many
SELECT 
    id,
    workspace_id,
    title,
    description,
    analysis_type,
    status,
    started_at,
    completed_at,
    config,
    error_message,
    created_at,
    updated_at
FROM analyses
WHERE 
    workspace_id = $1
    AND deleted_at IS NULL
    AND ($4::text IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAnalysesParams struct {
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	Limit       int32          `json:"limit"`
	Offset      int32          `json:"offset"`
	Status      sql.NullString `json:"status"`
}

type ListAnalysesRow struct {
	ID           uuid.UUID             `json:"id"`
	WorkspaceID  uuid.UUID             `json:"workspace_id"`
	Title        string                `json:"title"`
	Description  sql.NullString        `json:"description"`
	AnalysisType string                `json:"analysis_type"`
	Status       string                `json:"status"`
	StartedAt    sql.NullTime          `json:"started_at"`
	CompletedAt  sql.NullTime          `json:"completed_at"`
	Config       pqtype.NullRawMessage `json:"config"`
	ErrorMessage sql.NullString        `json:"error_message"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

func (q *Queries) ListAnalyses(ctx context.Context, arg ListAnalysesParams) ([]ListAnalysesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnalyses,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalysesRow
	for rows.Next() {
		var i ListAnalysesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Description,
			&i.AnalysisType,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Config,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisResults = `-- name: ListAnalysisResults :many
SELECT
    id,
    analysis_id,
    result_type,
    content,
    image_url,
    minio_bucket,
    minio_key,
    metadata,
    created_at
FROM analysis_results
WHERE 
    analysis_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAnalysisResults(ctx context.Context, analysisID uuid.UUID) ([]AnalysisResult, error) {
	rows, err := q.db.QueryContext(ctx, listAnalysisResults, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalysisResult
	for rows.Next() {
		var i AnalysisResult
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisID,
			&i.ResultType,
			&i.Content,
			&i.ImageUrl,
			&i.MinioBucket,
			&i.MinioKey,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnalysisStatus = `-- name: UpdateAnalysisStatus :exec
UPDATE analyses
SET
    status = $2,
    started_at = CASE
        WHEN $2 = 'processing' THEN now()
        ELSE started_at
    END,
    completed_at = CASE
        WHEN $2 IN ('completed', 'failed') THEN now()
        ELSE completed_at
    END,
    error_message = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateAnalysisStatusParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateAnalysisStatus(ctx context.Context, arg UpdateAnalysisStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAnalysisStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
