// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countChats = `-- name: CountChats :one
SELECT COUNT(*) 
FROM chats 
WHERE 
    workspace_id = $1 
    AND deleted_at IS NULL
`

func (q *Queries) CountChats(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChats, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChat = `-- name: CreateChat :one

INSERT INTO chats (
    workspace_id,
    title,
    filter_config,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, now(), now()
)
RETURNING id, workspace_id, title, filter_config, created_at, updated_at, deleted_at
`

type CreateChatParams struct {
	WorkspaceID  uuid.UUID             `json:"workspace_id"`
	Title        string                `json:"title"`
	FilterConfig pqtype.NullRawMessage `json:"filter_config"`
}

// ========================================
// Chat Operations
// ========================================
func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, arg.WorkspaceID, arg.Title, arg.FilterConfig)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.FilterConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (
    chat_id,
    role,
    content,
    message_index,
    document_refs,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, now()
)
RETURNING id, chat_id, role, content, message_index, document_refs, created_at
`

type CreateChatMessageParams struct {
	ChatID       uuid.UUID             `json:"chat_id"`
	Role         string                `json:"role"`
	Content      string                `json:"content"`
	MessageIndex int32                 `json:"message_index"`
	DocumentRefs pqtype.NullRawMessage `json:"document_refs"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage,
		arg.ChatID,
		arg.Role,
		arg.Content,
		arg.MessageIndex,
		arg.DocumentRefs,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Content,
		&i.MessageIndex,
		&i.DocumentRefs,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
UPDATE chats
SET 
    deleted_at = now(),
    updated_at = now()
WHERE 
    id = $1 
    AND workspace_id = $2 
    AND deleted_at IS NULL
`

type DeleteChatParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteChat(ctx context.Context, arg DeleteChatParams) error {
	_, err := q.db.ExecContext(ctx, deleteChat, arg.ID, arg.WorkspaceID)
	return err
}

const getChat = `-- name: GetChat :one
SELECT id, workspace_id, title, filter_config, created_at, updated_at, deleted_at FROM chats
WHERE 
    id = $1 
    AND workspace_id = $2 
    AND deleted_at IS NULL
`

type GetChatParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetChat(ctx context.Context, arg GetChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, arg.ID, arg.WorkspaceID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.FilterConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatMessageCount = `-- name: GetChatMessageCount :one
SELECT COUNT(*)::bigint as count
FROM chat_messages
WHERE chat_id = $1
`

func (q *Queries) GetChatMessageCount(ctx context.Context, chatID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChatMessageCount, chatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChatMessages = `-- name: GetChatMessages :many

SELECT 
    id,
    chat_id,
    role,
    content,
    message_index,
    document_refs,
    created_at
FROM chat_messages
WHERE 
    chat_id = $1
ORDER BY message_index ASC
LIMIT $2
`

type GetChatMessagesParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	Limit  int32     `json:"limit"`
}

// ========================================
// Chat Message Operations
// ========================================
func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessages, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Content,
			&i.MessageIndex,
			&i.DocumentRefs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastMessageTime = `-- name: GetLastMessageTime :one
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN MAX(created_at)
        ELSE NULL
    END::timestamptz as last_time
FROM chat_messages
WHERE chat_id = $1
`

func (q *Queries) GetLastMessageTime(ctx context.Context, chatID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLastMessageTime, chatID)
	var last_time time.Time
	err := row.Scan(&last_time)
	return last_time, err
}

const getMaxMessageIndex = `-- name: GetMaxMessageIndex :one
SELECT COALESCE(MAX(message_index), -1)::int as max_index
FROM chat_messages
WHERE chat_id = $1
`

func (q *Queries) GetMaxMessageIndex(ctx context.Context, chatID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxMessageIndex, chatID)
	var max_index int32
	err := row.Scan(&max_index)
	return max_index, err
}

const listChats = `-- name: ListChats :many
SELECT 
    c.id,
    c.workspace_id,
    c.title,
    c.filter_config,
    c.created_at,
    c.updated_at
FROM chats c
WHERE 
    c.workspace_id = $1 
    AND c.deleted_at IS NULL
ORDER BY c.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListChatsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListChatsRow struct {
	ID           uuid.UUID             `json:"id"`
	WorkspaceID  uuid.UUID             `json:"workspace_id"`
	Title        string                `json:"title"`
	FilterConfig pqtype.NullRawMessage `json:"filter_config"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

func (q *Queries) ListChats(ctx context.Context, arg ListChatsParams) ([]ListChatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChats, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatsRow
	for rows.Next() {
		var i ListChatsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.FilterConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatTimestamp = `-- name: UpdateChatTimestamp :exec
UPDATE chats
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateChatTimestamp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateChatTimestamp, id)
	return err
}
