// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    sha256_hash, 
    mime_type, 
    size_bytes, 
    original_filename, 
    minio_bucket, 
    minio_key,
    created_at,
    last_accessed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now(), now()
)
RETURNING id, sha256_hash, mime_type, size_bytes, original_filename, minio_bucket, minio_key, created_at, last_accessed_at
`

type CreateFileParams struct {
	Sha256Hash       string         `json:"sha256_hash"`
	MimeType         string         `json:"mime_type"`
	SizeBytes        int64          `json:"size_bytes"`
	OriginalFilename sql.NullString `json:"original_filename"`
	MinioBucket      string         `json:"minio_bucket"`
	MinioKey         string         `json:"minio_key"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.Sha256Hash,
		arg.MimeType,
		arg.SizeBytes,
		arg.OriginalFilename,
		arg.MinioBucket,
		arg.MinioKey,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Sha256Hash,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.MinioBucket,
		&i.MinioKey,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getFileByHash = `-- name: GetFileByHash :one
SELECT id, sha256_hash, mime_type, size_bytes, original_filename, minio_bucket, minio_key, created_at, last_accessed_at FROM files 
WHERE sha256_hash = $1 
LIMIT 1
`

func (q *Queries) GetFileByHash(ctx context.Context, sha256Hash string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByHash, sha256Hash)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Sha256Hash,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.MinioBucket,
		&i.MinioKey,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getFileById = `-- name: GetFileById :one
SELECT id, sha256_hash, mime_type, size_bytes, original_filename, minio_bucket, minio_key, created_at, last_accessed_at FROM files 
WHERE id = $1
`

func (q *Queries) GetFileById(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileById, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Sha256Hash,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.MinioBucket,
		&i.MinioKey,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const updateFileLastAccessed = `-- name: UpdateFileLastAccessed :exec
UPDATE files 
SET last_accessed_at = now() 
WHERE id = $1
`

func (q *Queries) UpdateFileLastAccessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateFileLastAccessed, id)
	return err
}
