// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graph_entities.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createGraphEntity = `-- name: CreateGraphEntity :one
INSERT INTO graph_entities (
    workspace_id,
    label,
    type,
    confidence,
    metadata
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, workspace_id, label, type, confidence, metadata, is_deleted, created_at, updated_at
`

type CreateGraphEntityParams struct {
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	Label       string          `json:"label"`
	Type        string          `json:"type"`
	Confidence  float64         `json:"confidence"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateGraphEntity(ctx context.Context, arg CreateGraphEntityParams) (GraphEntity, error) {
	row := q.db.QueryRowContext(ctx, createGraphEntity,
		arg.WorkspaceID,
		arg.Label,
		arg.Type,
		arg.Confidence,
		arg.Metadata,
	)
	var i GraphEntity
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Label,
		&i.Type,
		&i.Confidence,
		&i.Metadata,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGraphEntitiesByWorkspace = `-- name: GetGraphEntitiesByWorkspace :many
SELECT 
    id,
    workspace_id,
    label,
    type,
    confidence,
    metadata,
    is_deleted,
    created_at,
    updated_at
FROM graph_entities
WHERE workspace_id = $1
AND is_deleted = FALSE
ORDER BY created_at DESC
`

func (q *Queries) GetGraphEntitiesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]GraphEntity, error) {
	rows, err := q.db.QueryContext(ctx, getGraphEntitiesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphEntity
	for rows.Next() {
		var i GraphEntity
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Label,
			&i.Type,
			&i.Confidence,
			&i.Metadata,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGraphEntityByID = `-- name: GetGraphEntityByID :one
SELECT 
    id,
    workspace_id,
    label,
    type,
    confidence,
    metadata,
    is_deleted,
    created_at,
    updated_at
FROM graph_entities
WHERE id = $1
AND is_deleted = FALSE
`

func (q *Queries) GetGraphEntityByID(ctx context.Context, id uuid.UUID) (GraphEntity, error) {
	row := q.db.QueryRowContext(ctx, getGraphEntityByID, id)
	var i GraphEntity
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Label,
		&i.Type,
		&i.Confidence,
		&i.Metadata,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
