// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graphs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createGraph = `-- name: CreateGraph :one
INSERT INTO graphs (
    workspace_id,
    title,
    graph_type
) VALUES (
    $1, $2, $3
)
RETURNING id, workspace_id, title, graph_type, layout_config, created_at, updated_at, deleted_at
`

type CreateGraphParams struct {
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	Title       string         `json:"title"`
	GraphType   sql.NullString `json:"graph_type"`
}

func (q *Queries) CreateGraph(ctx context.Context, arg CreateGraphParams) (Graph, error) {
	row := q.db.QueryRowContext(ctx, createGraph, arg.WorkspaceID, arg.Title, arg.GraphType)
	var i Graph
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.GraphType,
		&i.LayoutConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createGraphEdge = `-- name: CreateGraphEdge :one
INSERT INTO graph_edges (
    graph_id,
    from_node_id,
    to_node_id,
    edge_type,
    is_directed,
    weight,
    confidence
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, graph_id, from_node_id, to_node_id, edge_type, is_directed, weight, confidence, style, metadata, created_at, updated_at
`

type CreateGraphEdgeParams struct {
	GraphID    uuid.UUID       `json:"graph_id"`
	FromNodeID uuid.UUID       `json:"from_node_id"`
	ToNodeID   uuid.UUID       `json:"to_node_id"`
	EdgeType   string          `json:"edge_type"`
	IsDirected bool            `json:"is_directed"`
	Weight     sql.NullFloat64 `json:"weight"`
	Confidence sql.NullFloat64 `json:"confidence"`
}

func (q *Queries) CreateGraphEdge(ctx context.Context, arg CreateGraphEdgeParams) (GraphEdge, error) {
	row := q.db.QueryRowContext(ctx, createGraphEdge,
		arg.GraphID,
		arg.FromNodeID,
		arg.ToNodeID,
		arg.EdgeType,
		arg.IsDirected,
		arg.Weight,
		arg.Confidence,
	)
	var i GraphEdge
	err := row.Scan(
		&i.ID,
		&i.GraphID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.EdgeType,
		&i.IsDirected,
		&i.Weight,
		&i.Confidence,
		&i.Style,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGraphNode = `-- name: CreateGraphNode :one
INSERT INTO graph_nodes (
    graph_id,
    label,
    node_type,
    source_type,
    source_id,
    style,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, graph_id, label, node_type, source_type, source_id, position, style, metadata, created_at
`

type CreateGraphNodeParams struct {
	GraphID    uuid.UUID             `json:"graph_id"`
	Label      string                `json:"label"`
	NodeType   string                `json:"node_type"`
	SourceType sql.NullString        `json:"source_type"`
	SourceID   uuid.NullUUID         `json:"source_id"`
	Style      pqtype.NullRawMessage `json:"style"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateGraphNode(ctx context.Context, arg CreateGraphNodeParams) (GraphNode, error) {
	row := q.db.QueryRowContext(ctx, createGraphNode,
		arg.GraphID,
		arg.Label,
		arg.NodeType,
		arg.SourceType,
		arg.SourceID,
		arg.Style,
		arg.Metadata,
	)
	var i GraphNode
	err := row.Scan(
		&i.ID,
		&i.GraphID,
		&i.Label,
		&i.NodeType,
		&i.SourceType,
		&i.SourceID,
		&i.Position,
		&i.Style,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGraph = `-- name: DeleteGraph :exec
UPDATE graphs
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeleteGraph(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGraph, id)
	return err
}

const deleteGraphNodesByGraphID = `-- name: DeleteGraphNodesByGraphID :exec
DELETE FROM graph_nodes WHERE graph_id = $1
`

func (q *Queries) DeleteGraphNodesByGraphID(ctx context.Context, graphID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGraphNodesByGraphID, graphID)
	return err
}

const getGraphByID = `-- name: GetGraphByID :one
SELECT 
    id,
    workspace_id,
    title,
    graph_type,
    layout_config,
    created_at,
    updated_at
FROM graphs
WHERE id = $1
  AND deleted_at IS NULL
`

type GetGraphByIDRow struct {
	ID           uuid.UUID             `json:"id"`
	WorkspaceID  uuid.UUID             `json:"workspace_id"`
	Title        string                `json:"title"`
	GraphType    sql.NullString        `json:"graph_type"`
	LayoutConfig pqtype.NullRawMessage `json:"layout_config"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

func (q *Queries) GetGraphByID(ctx context.Context, id uuid.UUID) (GetGraphByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGraphByID, id)
	var i GetGraphByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.GraphType,
		&i.LayoutConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGraphEdgesByGraphID = `-- name: GetGraphEdgesByGraphID :many
SELECT 
    id,
    graph_id,
    from_node_id,
    to_node_id,
    edge_type,
    is_directed,
    weight,
    confidence,
    style,
    metadata,
    created_at,
    updated_at
FROM graph_edges
WHERE graph_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetGraphEdgesByGraphID(ctx context.Context, graphID uuid.UUID) ([]GraphEdge, error) {
	rows, err := q.db.QueryContext(ctx, getGraphEdgesByGraphID, graphID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphEdge
	for rows.Next() {
		var i GraphEdge
		if err := rows.Scan(
			&i.ID,
			&i.GraphID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.EdgeType,
			&i.IsDirected,
			&i.Weight,
			&i.Confidence,
			&i.Style,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGraphNodesByGraphID = `-- name: GetGraphNodesByGraphID :many
SELECT 
    id,
    graph_id,
    label,
    node_type,
    source_type,
    source_id,
    position,
    style,
    metadata,
    created_at
FROM graph_nodes
WHERE graph_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetGraphNodesByGraphID(ctx context.Context, graphID uuid.UUID) ([]GraphNode, error) {
	rows, err := q.db.QueryContext(ctx, getGraphNodesByGraphID, graphID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphNode
	for rows.Next() {
		var i GraphNode
		if err := rows.Scan(
			&i.ID,
			&i.GraphID,
			&i.Label,
			&i.NodeType,
			&i.SourceType,
			&i.SourceID,
			&i.Position,
			&i.Style,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphsByWorkspace = `-- name: ListGraphsByWorkspace :many
SELECT 
    id,
    workspace_id,
    title,
    graph_type,
    created_at,
    updated_at
FROM graphs
WHERE workspace_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListGraphsByWorkspaceRow struct {
	ID          uuid.UUID      `json:"id"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	Title       string         `json:"title"`
	GraphType   sql.NullString `json:"graph_type"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) ListGraphsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListGraphsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listGraphsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGraphsByWorkspaceRow
	for rows.Next() {
		var i ListGraphsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.GraphType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGraph = `-- name: UpdateGraph :one
UPDATE graphs
SET 
    title = COALESCE($2::text, title),
    layout_config = COALESCE($3::jsonb, layout_config),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, workspace_id, title, graph_type, layout_config, created_at, updated_at, deleted_at
`

type UpdateGraphParams struct {
	ID           uuid.UUID             `json:"id"`
	Title        sql.NullString        `json:"title"`
	LayoutConfig pqtype.NullRawMessage `json:"layout_config"`
}

func (q *Queries) UpdateGraph(ctx context.Context, arg UpdateGraphParams) (Graph, error) {
	row := q.db.QueryRowContext(ctx, updateGraph, arg.ID, arg.Title, arg.LayoutConfig)
	var i Graph
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.GraphType,
		&i.LayoutConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
