// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graph_relations.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createGraphRelation = `-- name: CreateGraphRelation :one
INSERT INTO graph_relations (
    workspace_id,
    source_entity_id,
    target_entity_id,
    type,
    is_directed,
    weight,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, workspace_id, source_entity_id, target_entity_id, type, is_directed, weight, valid_from, valid_to, metadata, is_deleted, created_at, updated_at
`

type CreateGraphRelationParams struct {
	WorkspaceID    uuid.UUID       `json:"workspace_id"`
	SourceEntityID uuid.UUID       `json:"source_entity_id"`
	TargetEntityID uuid.UUID       `json:"target_entity_id"`
	Type           string          `json:"type"`
	IsDirected     bool            `json:"is_directed"`
	Weight         float64         `json:"weight"`
	Metadata       json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateGraphRelation(ctx context.Context, arg CreateGraphRelationParams) (GraphRelation, error) {
	row := q.db.QueryRowContext(ctx, createGraphRelation,
		arg.WorkspaceID,
		arg.SourceEntityID,
		arg.TargetEntityID,
		arg.Type,
		arg.IsDirected,
		arg.Weight,
		arg.Metadata,
	)
	var i GraphRelation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceEntityID,
		&i.TargetEntityID,
		&i.Type,
		&i.IsDirected,
		&i.Weight,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Metadata,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGraphRelationsByWorkspace = `-- name: GetGraphRelationsByWorkspace :many
SELECT 
    id,
    workspace_id,
    source_entity_id,
    target_entity_id,
    type,
    is_directed,
    weight,
    valid_from,
    valid_to,
    metadata,
    is_deleted,
    created_at,
    updated_at
FROM graph_relations
WHERE workspace_id = $1
  AND is_deleted = FALSE
ORDER BY created_at DESC
`

func (q *Queries) GetGraphRelationsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]GraphRelation, error) {
	rows, err := q.db.QueryContext(ctx, getGraphRelationsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphRelation
	for rows.Next() {
		var i GraphRelation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceEntityID,
			&i.TargetEntityID,
			&i.Type,
			&i.IsDirected,
			&i.Weight,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Metadata,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
