// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Analysis struct {
	ID           uuid.UUID             `json:"id"`
	WorkspaceID  uuid.UUID             `json:"workspace_id"`
	Title        string                `json:"title"`
	Description  sql.NullString        `json:"description"`
	AnalysisType string                `json:"analysis_type"`
	Status       string                `json:"status"`
	StartedAt    sql.NullTime          `json:"started_at"`
	CompletedAt  sql.NullTime          `json:"completed_at"`
	Config       pqtype.NullRawMessage `json:"config"`
	ErrorMessage sql.NullString        `json:"error_message"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
	DeletedAt    sql.NullTime          `json:"deleted_at"`
}

type AnalysisResult struct {
	ID          uuid.UUID             `json:"id"`
	AnalysisID  uuid.UUID             `json:"analysis_id"`
	ResultType  string                `json:"result_type"`
	Content     json.RawMessage       `json:"content"`
	ImageUrl    sql.NullString        `json:"image_url"`
	MinioBucket sql.NullString        `json:"minio_bucket"`
	MinioKey    sql.NullString        `json:"minio_key"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   time.Time             `json:"created_at"`
}

type CanvasElement struct {
	ID          uuid.UUID             `json:"id"`
	CanvasID    uuid.UUID             `json:"canvas_id"`
	ElementType string                `json:"element_type"`
	Position    json.RawMessage       `json:"position"`
	ZIndex      int32                 `json:"z_index"`
	Content     json.RawMessage       `json:"content"`
	Style       pqtype.NullRawMessage `json:"style"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
	DeletedAt   sql.NullTime          `json:"deleted_at"`
}

type Canvase struct {
	ID          uuid.UUID             `json:"id"`
	WorkspaceID uuid.UUID             `json:"workspace_id"`
	Title       string                `json:"title"`
	Description sql.NullString        `json:"description"`
	Settings    pqtype.NullRawMessage `json:"settings"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
	DeletedAt   sql.NullTime          `json:"deleted_at"`
}

type Chat struct {
	ID           uuid.UUID             `json:"id"`
	WorkspaceID  uuid.UUID             `json:"workspace_id"`
	Title        string                `json:"title"`
	FilterConfig pqtype.NullRawMessage `json:"filter_config"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
	DeletedAt    sql.NullTime          `json:"deleted_at"`
}

type ChatMessage struct {
	ID           uuid.UUID             `json:"id"`
	ChatID       uuid.UUID             `json:"chat_id"`
	Role         string                `json:"role"`
	Content      string                `json:"content"`
	MessageIndex int32                 `json:"message_index"`
	DocumentRefs pqtype.NullRawMessage `json:"document_refs"`
	CreatedAt    time.Time             `json:"created_at"`
}

type Directory struct {
	ID          uuid.UUID     `json:"id"`
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	ParentID    uuid.NullUUID `json:"parent_id"`
	Name        string        `json:"name"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
}

type Document struct {
	ID          uuid.UUID             `json:"id"`
	WorkspaceID uuid.UUID             `json:"workspace_id"`
	DirectoryID uuid.NullUUID         `json:"directory_id"`
	FileID      uuid.UUID             `json:"file_id"`
	Name        string                `json:"name"`
	Tags        []string              `json:"tags"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	Status      string                `json:"status"`
	ProcessedAt sql.NullTime          `json:"processed_at"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
	DeletedAt   sql.NullTime          `json:"deleted_at"`
}

type DocumentChunk struct {
	ID            uuid.UUID             `json:"id"`
	DocumentID    uuid.UUID             `json:"document_id"`
	ChunkIndex    int32                 `json:"chunk_index"`
	Content       string                `json:"content"`
	QdrantPointID uuid.NullUUID         `json:"qdrant_point_id"`
	Metadata      pqtype.NullRawMessage `json:"metadata"`
	CreatedAt     time.Time             `json:"created_at"`
	PageNumber    int32                 `json:"page_number"`
}

type File struct {
	ID               uuid.UUID      `json:"id"`
	Sha256Hash       string         `json:"sha256_hash"`
	MimeType         string         `json:"mime_type"`
	SizeBytes        int64          `json:"size_bytes"`
	OriginalFilename sql.NullString `json:"original_filename"`
	MinioBucket      string         `json:"minio_bucket"`
	MinioKey         string         `json:"minio_key"`
	CreatedAt        time.Time      `json:"created_at"`
	LastAccessedAt   sql.NullTime   `json:"last_accessed_at"`
}

type Graph struct {
	ID           uuid.UUID             `json:"id"`
	WorkspaceID  uuid.UUID             `json:"workspace_id"`
	Title        string                `json:"title"`
	GraphType    sql.NullString        `json:"graph_type"`
	LayoutConfig pqtype.NullRawMessage `json:"layout_config"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
	DeletedAt    sql.NullTime          `json:"deleted_at"`
}

type GraphEdge struct {
	ID         uuid.UUID             `json:"id"`
	GraphID    uuid.UUID             `json:"graph_id"`
	FromNodeID uuid.UUID             `json:"from_node_id"`
	ToNodeID   uuid.UUID             `json:"to_node_id"`
	EdgeType   string                `json:"edge_type"`
	IsDirected bool                  `json:"is_directed"`
	Weight     sql.NullFloat64       `json:"weight"`
	Confidence sql.NullFloat64       `json:"confidence"`
	Style      pqtype.NullRawMessage `json:"style"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	CreatedAt  time.Time             `json:"created_at"`
	UpdatedAt  time.Time             `json:"updated_at"`
}

type GraphEntity struct {
	ID          uuid.UUID       `json:"id"`
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	Label       string          `json:"label"`
	Type        string          `json:"type"`
	Confidence  float64         `json:"confidence"`
	Metadata    json.RawMessage `json:"metadata"`
	IsDeleted   bool            `json:"is_deleted"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type GraphNode struct {
	ID         uuid.UUID             `json:"id"`
	GraphID    uuid.UUID             `json:"graph_id"`
	Label      string                `json:"label"`
	NodeType   string                `json:"node_type"`
	SourceType sql.NullString        `json:"source_type"`
	SourceID   uuid.NullUUID         `json:"source_id"`
	Position   pqtype.NullRawMessage `json:"position"`
	Style      pqtype.NullRawMessage `json:"style"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	CreatedAt  time.Time             `json:"created_at"`
}

type GraphRelation struct {
	ID             uuid.UUID       `json:"id"`
	WorkspaceID    uuid.UUID       `json:"workspace_id"`
	SourceEntityID uuid.UUID       `json:"source_entity_id"`
	TargetEntityID uuid.UUID       `json:"target_entity_id"`
	Type           string          `json:"type"`
	IsDirected     bool            `json:"is_directed"`
	Weight         float64         `json:"weight"`
	ValidFrom      sql.NullTime    `json:"valid_from"`
	ValidTo        sql.NullTime    `json:"valid_to"`
	Metadata       json.RawMessage `json:"metadata"`
	IsDeleted      bool            `json:"is_deleted"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type Workspace struct {
	ID          uuid.UUID             `json:"id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Settings    pqtype.NullRawMessage `json:"settings"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
	DeletedAt   sql.NullTime          `json:"deleted_at"`
}
