// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getChunksByIDs = `-- name: GetChunksByIDs :many

SELECT 
    id,
    document_id,
    chunk_index,
    page_number,
    content,
    created_at
FROM document_chunks
WHERE id = ANY($1::uuid[])
`

type GetChunksByIDsRow struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	ChunkIndex int32     `json:"chunk_index"`
	PageNumber int32     `json:"page_number"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
}

// apps/api-gateway/queries/search.sql
// page_number を追加して返す
func (q *Queries) GetChunksByIDs(ctx context.Context, chunkIds []uuid.UUID) ([]GetChunksByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getChunksByIDs, pq.Array(chunkIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChunksByIDsRow
	for rows.Next() {
		var i GetChunksByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.PageNumber,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByChunkIDs = `-- name: GetDocumentsByChunkIDs :many
SELECT DISTINCT
    d.id,
    d.name,
    d.workspace_id
FROM documents d
INNER JOIN document_chunks dc ON d.id = dc.document_id
WHERE dc.id = ANY($1::uuid[])
`

type GetDocumentsByChunkIDsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetDocumentsByChunkIDs(ctx context.Context, chunkIds []uuid.UUID) ([]GetDocumentsByChunkIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentsByChunkIDs, pq.Array(chunkIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentsByChunkIDsRow
	for rows.Next() {
		var i GetDocumentsByChunkIDsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.WorkspaceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
