// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getDocumentMetadataByIDs = `-- name: GetDocumentMetadataByIDs :many
SELECT 
    d.id,
    d.name,
    f.mime_type,
    f.size_bytes,
    d.created_at,
    d.updated_at
FROM documents d
INNER JOIN files f ON d.file_id = f.id
WHERE 
    d.id = ANY($1::uuid[])
    AND d.workspace_id = $2
    AND d.deleted_at IS NULL
ORDER BY d.name
`

type GetDocumentMetadataByIDsParams struct {
	DocumentIds []uuid.UUID `json:"document_ids"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
}

type GetDocumentMetadataByIDsRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	MimeType  string    `json:"mime_type"`
	SizeBytes int64     `json:"size_bytes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ドキュメントのメタデータのみ取得（チャンク内容は不要）
func (q *Queries) GetDocumentMetadataByIDs(ctx context.Context, arg GetDocumentMetadataByIDsParams) ([]GetDocumentMetadataByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentMetadataByIDs, pq.Array(arg.DocumentIds), arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentMetadataByIDsRow
	for rows.Next() {
		var i GetDocumentMetadataByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
