// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"error,omitempty"`
}

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt   time.Time               `json:"created_at"`
	Description *string                 `json:"description"`
	Id          openapi_types.UUID      `json:"id"`
	Name        string                  `json:"name"`
	Settings    *map[string]interface{} `json:"settings"`
	UpdatedAt   time.Time               `json:"updated_at"`
}

// NotFound defines model for NotFound.
type NotFound = Error

// CreateWorkspaceJSONBody defines parameters for CreateWorkspace.
type CreateWorkspaceJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// UpdateWorkspaceJSONBody defines parameters for UpdateWorkspace.
type UpdateWorkspaceJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody CreateWorkspaceJSONBody

// UpdateWorkspaceJSONRequestBody defines body for UpdateWorkspace for application/json ContentType.
type UpdateWorkspaceJSONRequestBody UpdateWorkspaceJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// API to check the health
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// get all workspaces
	// (GET /workspaces)
	ListWorkspaces(w http.ResponseWriter, r *http.Request)
	// create workspace
	// (POST /workspaces)
	CreateWorkspace(w http.ResponseWriter, r *http.Request)
	// Delete workspace
	// (DELETE /workspaces/{workspaceId})
	DeleteWorkspace(w http.ResponseWriter, r *http.Request, workspaceId openapi_types.UUID)
	// Get workspace by id
	// (GET /workspaces/{workspaceId})
	GetWorkspace(w http.ResponseWriter, r *http.Request, workspaceId openapi_types.UUID)
	// Update workspace
	// (PATCH /workspaces/{workspaceId})
	UpdateWorkspace(w http.ResponseWriter, r *http.Request, workspaceId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// API to check the health
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// get all workspaces
// (GET /workspaces)
func (_ Unimplemented) ListWorkspaces(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// create workspace
// (POST /workspaces)
func (_ Unimplemented) CreateWorkspace(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete workspace
// (DELETE /workspaces/{workspaceId})
func (_ Unimplemented) DeleteWorkspace(w http.ResponseWriter, r *http.Request, workspaceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get workspace by id
// (GET /workspaces/{workspaceId})
func (_ Unimplemented) GetWorkspace(w http.ResponseWriter, r *http.Request, workspaceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update workspace
// (PATCH /workspaces/{workspaceId})
func (_ Unimplemented) UpdateWorkspace(w http.ResponseWriter, r *http.Request, workspaceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkspaces operation middleware
func (siw *ServerInterfaceWrapper) ListWorkspaces(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkspaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWorkspace operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkspace(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorkspace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWorkspace operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWorkspace(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWorkspace operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", chi.URLParam(r, "workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWorkspace(w, r, workspaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workspaces", wrapper.ListWorkspaces)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/workspaces", wrapper.CreateWorkspace)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/workspaces/{workspaceId}", wrapper.DeleteWorkspace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workspaces/{workspaceId}", wrapper.GetWorkspace)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/workspaces/{workspaceId}", wrapper.UpdateWorkspace)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWXU/cOhD9K9bc+5i7CRceUN6AtnTViiKkige0qkw8uzEktmtPlq5W+e+VHZYkm2z5",
	"FOoTxnZm5pw5Z7xryHRptEJFDtI1WHRGK4fhnzNNn3SlhF9nWhEq8ktuTCEzTlKr+MZp5fdclmPJ/epf",
	"i3NI4Z+4DRw3py7+aK22UNd1BAJdZqXxQSCFC3S6shkypYnNQ05/6f47H7b5NF2DsdqgJdmUiOPbmRbo",
	"/9LKIKTgyEq1gDqCEp3ji7GzOtrs6OsbzGhsJ4JLbW+d4RmO5LTICcUPHkiaa1v6FQhO+B/JEiEaltNj",
	"YQ2qKgp+XSCkZCscuS9FL3ZVSTEWVvFyHL5DIqkWoV4uhPSJeXHewdEk3lFIy0NlxDPB1hFY/FlJiwLS",
	"KwiFhzqjLnO9yLNhSzwHaq590r6Cjs6njs21ZZQjcytHWPoaJHkQcIa/KseOzqcQwRKta77ZmySTxKPR",
	"BhU3ElLYnySTfYjAcMoDS3GOvKDcLxcYwHqugvinAlL4HI5PcsxuIerb5/8keZZz+nJyxKlyTxPqwE/f",
	"vjT+qcqS21VDDyPNMl9noOgelr8V321E7XbC/CodXbbX3hRpP70kLN1jg6S1YcsGt5avxunpc7FAYrwo",
	"2F0XD3HviqtuMbM6AqPdCBsnQbBtEY200dGxFqtXMLE1Dp7q6y1rhVvj3mmveV/Xgzbuvdmo73RoKM+G",
	"P+EhHTxTOi96Xo65YBdNh7Z80YyeVgq7lNC3Sbx+WE9F3XSuQMKhUj6E/b5SeowfDEfZmWYn93QEgg52",
	"4X4IFT+81H10TfYOujoat/cp0h9qTN5HFX5ovQ7vKVILll2vmAwaM9zyEgmt7+sapE/mB/zmBUqh007Y",
	"dknUwfbIy1vPwsuR5UOGv4dn7W8aGS8YD+8khIYr8Vo1NGG66g/naJcbJfTTFjrjBRO4xEKbEhUxVEtp",
	"tfJr/8vEFpBCTmTSOA6Xc+0oPUwOk5gbGS/3oJ7VvwMAAP//zR0Be1ILAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
